### ISSUE TITLE
Skin does not work with Maven Site Plugin 3.5

### ISSUE THREAD

**Issue by bindul** [andriusvelykis/reflow-maven-skin#49]
The changes introduced in Maven Site Plugin breaks the skin. Maven Site 3.5 introduced some non backward compatible changes [From 3.4 to 3.5](https://maven.apache.org/plugins/maven-site-plugin/migrate.html#From_3.4_to_3.5)

Among other issues, the body is rendered as:

```
<div class="body-content">
$bodyWithHeader
</div>
```

**Comment by Bernardo-MG** [comment]
The root problem is that the new Maven Site plugin is not loading Velocity tools.

See:
http://maven.40175.n5.nabble.com/New-maven-site-and-doxia-with-custom-velocity-doxia-td5865376.html

**Comment by marvec** [comment]
I am experiencing the same issue and a fix would be highly appreciated.

**Comment by Bernardo-MG** [comment]
As I've been completely unable to find a fix to this problem, and it seems everybody else is in the same situation, I've opened an issue for the Maven Site plugin:
https://issues.apache.org/jira/browse/MSITE-782

**Comment by michael-o** [comment]
This issue has been fixed in https://issues.apache.org/jira/browse/DOXIASITETOOLS-168 and needs some trivial changes in this plugin.

**Comment by Bernardo-MG** [comment]
Thanks for the fix

**Comment by solomax** [comment]
Recently tried with Maven Site Plugin 3.6 and this issue is not fixed :(

**Comment by bindul** [comment]
@solomax, as noted above (by @michael-o):
> This issue has been fixed in https://issues.apache.org/jira/browse/DOXIASITETOOLS-168 and **needs some trivial changes in this plugin**.

The plugin still needs a change, I believe around moving [reflow-maven-skin/reflow-velocity-tools/src/main/resources/tools.xml](https://github.com/andriusvelykis/reflow-maven-skin/blob/01170ae1426a1adfe7cc9c199e77aaa2ecb37ef2/reflow-velocity-tools/src/main/resources/tools.xml) to 
`META-INF/maven/site-tools.xml` (or moving it there during the build), as suggested in [DOXIASITETOOLS-168 comment-15578066](https://issues.apache.org/jira/browse/DOXIASITETOOLS-168?focusedCommentId=15578066&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15578066).

Have not tested.

**Comment by Bernardo-MG** [comment]
I've updated my own skin for working with Maven Site 3.6: https://github.com/Bernardo-MG/docs-maven-skin

As commented, from now on any custom tool should move the tools.xml file to `META-INF/maven/site-tools.xml`

**Comment by Ordiel** [comment]
Should we fork this project? @andriusvelykis does not seam to be active on this repo any more (for about 5 years now)

**Comment by solomax** [comment]
@Ordiel we are using this one https://github.com/devacfr/reflow-maven-skin
